### ISSUE TITLE
Does this plugin work on version 3.0, 3.1?

### ISSUE THREAD

**Issue by zfilin** [twinslash/redmine_tracker_accessible#6]

**Comment by drewripa** [comment]
tested on 3.0
work fine (change special permissions in Task section of roles)

**Comment by archonwang** [comment]
tested on Redmine 3.2.2
urrr
there's some error when Open the create new issue as follow:

> I, [2016-05-15T11:51:42.807876 #20304]  INFO -- : Started GET "/plugin_assets/redmine_tracker_accessible/images/bullet_add.png" for 192.168.60.239 at 2016-05-15 11:51:42 +0800
> F, [2016-05-15T11:51:42.809977 #20304] FATAL -- : 
> ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_tracker_accessible/images/bullet_add.png"):
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
>   railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
>   railties (4.2.5.2) lib/rails/rack/logger.rb:22:in`call'
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
>   rack (1.6.4) lib/rack/methodoverride.rb:22:in`call'
>   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
>   activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/static.rb:116:in `call'
>   rack (1.6.4) lib/rack/sendfile.rb:113:in`call'
>   railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
>   railties (4.2.5.2) lib/rails/application.rb:165:in`call'
>   railties (4.2.5.2) lib/rails/railtie.rb:194:in `public_send'
>   railties (4.2.5.2) lib/rails/railtie.rb:194:in`method_missing'
>   thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
>   thin (1.6.4) lib/thin/connection.rb:84:in`catch'
>   thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
>   thin (1.6.4) lib/thin/connection.rb:53:in`process'
>   thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
>   eventmachine (1.2.0.1) lib/eventmachine.rb:194:in`run_machine'
>   eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
>   thin (1.6.4) lib/thin/backends/base.rb:73:in`start'
>   thin (1.6.4) lib/thin/server.rb:162:in `start'
>   thin (1.6.4) lib/thin/controllers/controller.rb:87:in`start'
>   thin (1.6.4) lib/thin/runner.rb:200:in `run_command'
>   thin (1.6.4) lib/thin/runner.rb:156:in`run!'
>   thin (1.6.4) bin/thin:6:in `<top (required)>'
>   /usr/local/rvm/gems/ruby-2.2.4@newgemset/bin/thin:23:in`load'
>   /usr/local/rvm/gems/ruby-2.2.4@newgemset/bin/thin:23:in `<main>'
